server:
  port: 8080

openai:
  api-key: ${OPENAI_API_KEY}

voice:
  elevenlabs:
    api-key: ${ELEVENLABS_API_KEY}
    fornitore-agent-id: ${ELEVENLABS_FORNITORE_AGENT_ID}
    agent-phone-number-id: ${ELEVENLABS_AGENT_PHONE_NUMBER_ID}
    pre-call-token: ${ELEVENLABS_PRE_CALL_TOKEN}
    outbound-url: https://api.elevenlabs.io/v1/convai/sip-trunk/outbound-call
    job-call-outbound-delay-ms: 10000

whatsapp:
  token: ${WHATSAPP_TOKEN}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID}
  verify-token: ${WHATSAPP_VERIFY_TOKEN}
  
  spring:
    datasource:
      url: jdbc:postgresql://postgres.railway.internal:5432/railway?sslmode=require
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

      hikari:
        connection-init-sql: SET TIME ZONE 'Europe/Rome'

    jackson:
      time-zone: Europe/Rome

lucrezia:
  api-public-base-url: https://api.lucreziaai.it
  api-public-secret: ${LUCREZIA_API_SECRET}
  dashboard-public-base-url: #